version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - net
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exchange-rate-api
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - net
    ports:
      - 3000:3000

volumes:
  postgres_data:

networks:
  net:
    driver: bridge
